[package]
name = "terrain-godot"
description = "OpenTerrainStudio GDExtension: exposes terrain-core to the Godot app."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
rayon.workspace = true
terrain-core.workspace = true
terrain-nodes.workspace = true
godot.workspace = true
serde_json.workspace = true
